const policyOptions: any = [
  { label: "Yes", value: "yes" },
  { label: "No", value: "no" },
];

export const formdata: any = [
  {
    title: "Business Details",
    type: "title",
    tag: "title",
  },
  {
    title: "vendorID",
    description: "Enter your vendorID",
    tag: "text",
    required: true,
    name: "vendorID",
    type: "text",
  },
  {
    title: "legal Name",
    description: "Enter your legal name",
    tag: "text",
    required: true,
    name: "legalName",
    type: "text",
  },
  {
    title: "Trade Number",
    description: "Enter your Trade Number",
    tag: "text",
    required: true,
    name: "tradeNumber",
    type: "text",
  },
  {
    title: "Vender State",
    description: "Enter your Vender State",
    tag: "text",
    required: true,
    name: "venderState",
    type: "text",
  },
  {
    title: "Vender Location",
    description: "Enter your Vender Location",
    tag: "text",
    required: true,
    name: "venderLocation",
    type: "text",
  },
  {
    title: "GST Registered",
    description: "Enter your GST Registered",
    tag: "select",
    required: false,
    name: "gstRegistered",
    type: "select",
  },
  {
    title: "GST Certificate",
    description: "Upload your GST Certificate",
    tag: "file",
    required: false,
    name: "gstCertificate",
    type: "file",
  },
  {
    title: "Payment Terms",
    description: "Enter your Payment Terms",
    tag: "text",
    required: true,
    name: "paymentTerms",
    type: "text",
  },
  {
    title: " PAN Attachment",
    description: "Upload your PAN Attachment",
    tag: "file",
    required: false,
    name: "panAttachment",
    type: "file",
  },
  {
    title: "Policy",
    description: "Enter your Policy",
    tag: "select",
    required: true,
    name: "policy",
    type: "select",
    options: policyOptions,
  },

  {
    title: "Vender Address",
    description: "Enter your Vender Address",
    tag: "text",
    required: true,
    name: "venderAddress",
    type: "text",
  },

  {
    title: "MSME Details",
    type: "title",
    tag: "title",
  },
  {
    title: "MSME Certificate",
    description: "Upload your MSME Certificate",
    tag: "text",
    required: false,
    name: "msmeCertificate",
    type: "text",
  },
  {
    title: "MSME Certificate Attachment",
    description: "Upload your MSME Certificate Attachment",
    tag: "file",
    required: false,
    name: "msmeCertificateAttachment",
    type: "file",
  },
  {
    title: "Lower Exception",
    description: "Enter your Lower Exception",
    tag: "text",
    required: true,
    name: "lowerException",
    type: "text",
  },
  {
    title: "Lower Exception Certificate",
    description: "Upload your Lower Exception Certificate",
    tag: "file",
    required: false,
    name: "lowerExceptionCertificate",
    type: "file",
  },
];
